In [51]:
import numpy as np

In [52]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [53]:
np.arange(3,13,3)

array([ 3,  6,  9, 12])

In [54]:
c = np.zeros((5,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
d = np.arange(500,9500,1).reshape(100,90)
print(d)

[[ 500  501  502 ...  587  588  589]
 [ 590  591  592 ...  677  678  679]
 [ 680  681  682 ...  767  768  769]
 ...
 [9230 9231 9232 ... 9317 9318 9319]
 [9320 9321 9322 ... 9407 9408 9409]
 [9410 9411 9412 ... 9497 9498 9499]]


In [56]:
e = np.arange(1,101,1)
print(e[54:88])

[55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78
 79 80 81 82 83 84 85 86 87 88]
